# -*- coding: utf-8 -*-

from PyQt5 import QtCore, QtWidgets
import pyqtgraph as pg

class Ui_Attitude(object):
    
    
    def setupUi(self, Attitude):
        Attitude.setObjectName("Attitude")
        Attitude.resize(966, 750)
        self.label = QtWidgets.QLabel(Attitude)
        self.label.setGeometry(QtCore.QRect(230, 20, 21, 16))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Attitude)
        self.label_2.setGeometry(QtCore.QRect(320, 20, 21, 20))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Attitude)
        self.label_3.setGeometry(QtCore.QRect(410, 20, 21, 16))
        self.label_3.setObjectName("label_3")
        self.calculate = QtWidgets.QPushButton(Attitude)
        self.calculate.setGeometry(QtCore.QRect(40, 20, 88, 34))
        self.calculate.setObjectName("calculate")
        self.clear = QtWidgets.QPushButton(Attitude)
        self.clear.setGeometry(QtCore.QRect(850, 20, 88, 34))
        self.clear.setObjectName("clear")
        self.simulate = QtWidgets.QPushButton(Attitude)
        self.simulate.setGeometry(QtCore.QRect(800, 660, 120, 50))
        self.simulate.setObjectName("simulate")
        self.Wx = QtWidgets.QDoubleSpinBox(Attitude)
        self.Wx.setGeometry(QtCore.QRect(210, 50, 71, 32))
        self.Wx.setDecimals(3)
        self.Wx.setMinimum(-1000000000.0)
        self.Wx.setMaximum(1000000000.0)
        self.Wx.setObjectName("Wx")
        self.Wy = QtWidgets.QDoubleSpinBox(Attitude)
        self.Wy.setGeometry(QtCore.QRect(300, 50, 71, 32))
        self.Wy.setDecimals(3)
        self.Wy.setMinimum(-1000000000.0)
        self.Wy.setMaximum(1000000000.0)
        self.Wy.setObjectName("Wy")
        self.Wz = QtWidgets.QDoubleSpinBox(Attitude)
        self.Wz.setGeometry(QtCore.QRect(390, 50, 71, 32))
        self.Wz.setDecimals(3)
        self.Wz.setMinimum(-1000000000.0)
        self.Wz.setMaximum(1000000000.0)
        self.Wz.setObjectName("Wz")
        self.graphicsView_x = pg.PlotWidget(Attitude)
        self.graphicsView_x.setGeometry(QtCore.QRect(160, 110, 791, 171))
        self.graphicsView_x.setObjectName("graphicsView_x")
        self.graphicsView_y = pg.PlotWidget(Attitude)
        self.graphicsView_y.setGeometry(QtCore.QRect(160, 290, 791, 171))
        self.graphicsView_y.setObjectName("graphicsView_y")
        self.graphicsView_z = pg.PlotWidget(Attitude)
        self.graphicsView_z.setGeometry(QtCore.QRect(160, 470, 791, 171))
        self.graphicsView_z.setObjectName("graphicsView_z")
        self.label_4 = QtWidgets.QLabel(Attitude)
        self.label_4.setGeometry(QtCore.QRect(70, 180, 58, 18))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Attitude)
        self.label_5.setGeometry(QtCore.QRect(70, 370, 58, 18))
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(Attitude)
        self.label_6.setGeometry(QtCore.QRect(70, 540, 58, 18))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(Attitude)
        self.label_7.setGeometry(QtCore.QRect(710, 20, 21, 16))
        self.label_7.setObjectName("label_7")
        self.Jyy = QtWidgets.QDoubleSpinBox(Attitude)
        self.Jyy.setGeometry(QtCore.QRect(600, 50, 71, 32))
        self.Jyy.setDecimals(3)
        self.Jyy.setMinimum(-1000000000.0)
        self.Jyy.setMaximum(1000000000.0)
        self.Jyy.setObjectName("Jyy")
        self.label_8 = QtWidgets.QLabel(Attitude)
        self.label_8.setGeometry(QtCore.QRect(530, 20, 21, 16))
        self.label_8.setObjectName("label_8")
        self.Jxx = QtWidgets.QDoubleSpinBox(Attitude)
        self.Jxx.setGeometry(QtCore.QRect(510, 50, 71, 32))
        self.Jxx.setDecimals(3)
        self.Jxx.setMinimum(-1000000000.0)
        self.Jxx.setMaximum(1000000000.0)
        self.Jxx.setObjectName("Jxx")
        self.label_9 = QtWidgets.QLabel(Attitude)
        self.label_9.setGeometry(QtCore.QRect(630, 20, 21, 20))
        self.label_9.setObjectName("label_9")
        self.Jzz = QtWidgets.QDoubleSpinBox(Attitude)
        self.Jzz.setGeometry(QtCore.QRect(690, 50, 71, 32))
        self.Jzz.setDecimals(3)
        self.Jzz.setMinimum(-1000000000.0)
        self.Jzz.setMaximum(1000000000.0)
        self.Jzz.setObjectName("Jzz")
        self.Hr = QtWidgets.QCheckBox(Attitude)
        self.Hr.setGeometry(QtCore.QRect(20, 70, 141, 22))
        self.Hr.setObjectName("Hr")
        self.Hr.setChecked(False)

        self.retranslateUi(Attitude)
        QtCore.QMetaObject.connectSlotsByName(Attitude)
        
    def retranslateUi(self, Attitude):
        _translate = QtCore.QCoreApplication.translate
        Attitude.setWindowTitle(_translate("Attitude", "Dialog"))
        self.label.setText(_translate("Attitude", "Wx"))
        self.label_2.setText(_translate("Attitude", "Wy"))
        self.label_3.setText(_translate("Attitude", "Wz"))
        self.calculate.setText(_translate("Attitude", "Calculate"))
        self.clear.setText(_translate("Attitude", "Clear"))
        self.simulate.setText(_translate("Attitude", "Simulate"))
        self.label_4.setText(_translate("Attitude", "Wx"))
        self.label_5.setText(_translate("Attitude", "Wy"))
        self.label_6.setText(_translate("Attitude", "Wz"))
        self.label_7.setText(_translate("Attitude", "Jzz"))
        self.label_8.setText(_translate("Attitude", "Jxx"))
        self.label_9.setText(_translate("Attitude", "Jyy"))
        self.Hr.setText(_translate("Attitude", "Rotor Momentum"))


